// The sensor catalog: SMC keys, their names and the chips they appear on,
// generated from the Stats app's Modules/Sensors/values.swift (version 3.0.19,
// MIT licence, Copyright (c) 2019 Serhiy Mytrovtsiy; see LICENSE-stats.txt beside
// this file). A "%" in a key stands for any one character, and in a name for the
// character it matched. `core` marks the CPU and GPU core sensors whose readings
// make the menu bar's CPU and GPU figures.

let sensorCatalog: [CatalogSensor] = [
    CatalogSensor(key: "TA%P", name: "Ambient %", group: .sensor, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "Th%H", name: "Heatpipe %", group: .sensor, kind: .temperature, chips: [.intel], core: false),
    CatalogSensor(key: "TZ%C", name: "Thermal zone %", group: .sensor, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "TC0D", name: "CPU diode", group: .cpu, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "TC0E", name: "CPU diode virtual", group: .cpu, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "TC0F", name: "CPU diode filtered", group: .cpu, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "TC0H", name: "CPU heatsink", group: .cpu, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "TC0P", name: "CPU proximity", group: .cpu, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "TCAD", name: "CPU package", group: .cpu, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "TC%c", name: "CPU core %", group: .cpu, kind: .temperature, chips: nil, core: true),
    CatalogSensor(key: "TC%C", name: "CPU Core %", group: .cpu, kind: .temperature, chips: nil, core: true),
    CatalogSensor(key: "TCGC", name: "GPU Intel Graphics", group: .gpu, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "TG0D", name: "GPU diode", group: .gpu, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "TGDD", name: "GPU AMD Radeon", group: .gpu, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "TG0H", name: "GPU heatsink", group: .gpu, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "TG0P", name: "GPU proximity", group: .gpu, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "Tm0P", name: "Mainboard", group: .system, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "Tp0P", name: "Powerboard", group: .system, kind: .temperature, chips: [.intel], core: false),
    CatalogSensor(key: "TB1T", name: "Battery", group: .system, kind: .temperature, chips: [.intel], core: false),
    CatalogSensor(key: "TW0P", name: "Airport", group: .system, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "TL0P", name: "Display", group: .system, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "TI%P", name: "Thunderbolt %", group: .system, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "TH%A", name: "Disk % (A)", group: .system, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "TH%B", name: "Disk % (B)", group: .system, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "TH%C", name: "Disk % (C)", group: .system, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "TTLD", name: "Thunderbolt left", group: .system, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "TTRD", name: "Thunderbolt right", group: .system, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "TN0D", name: "Northbridge diode", group: .system, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "TN0H", name: "Northbridge heatsink", group: .system, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "TN0P", name: "Northbridge proximity", group: .system, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "Tp09", name: "CPU efficiency core 1", group: .cpu, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra], core: true),
    CatalogSensor(key: "Tp0T", name: "CPU efficiency core 2", group: .cpu, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra], core: true),
    CatalogSensor(key: "Tp01", name: "CPU performance core 1", group: .cpu, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra], core: true),
    CatalogSensor(key: "Tp05", name: "CPU performance core 2", group: .cpu, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra], core: true),
    CatalogSensor(key: "Tp0D", name: "CPU performance core 3", group: .cpu, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra], core: true),
    CatalogSensor(key: "Tp0H", name: "CPU performance core 4", group: .cpu, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra], core: true),
    CatalogSensor(key: "Tp0L", name: "CPU performance core 5", group: .cpu, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra], core: true),
    CatalogSensor(key: "Tp0P", name: "CPU performance core 6", group: .cpu, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra], core: true),
    CatalogSensor(key: "Tp0X", name: "CPU performance core 7", group: .cpu, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra], core: true),
    CatalogSensor(key: "Tp0b", name: "CPU performance core 8", group: .cpu, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra], core: true),
    CatalogSensor(key: "Tg05", name: "GPU 1", group: .gpu, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra], core: true),
    CatalogSensor(key: "Tg0D", name: "GPU 2", group: .gpu, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra], core: true),
    CatalogSensor(key: "Tg0L", name: "GPU 3", group: .gpu, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra], core: true),
    CatalogSensor(key: "Tg0T", name: "GPU 4", group: .gpu, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra], core: true),
    CatalogSensor(key: "Tm02", name: "Memory 1", group: .sensor, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra], core: false),
    CatalogSensor(key: "Tm06", name: "Memory 2", group: .sensor, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra], core: false),
    CatalogSensor(key: "Tm08", name: "Memory 3", group: .sensor, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra], core: false),
    CatalogSensor(key: "Tm09", name: "Memory 4", group: .sensor, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra], core: false),
    CatalogSensor(key: "Tp1h", name: "CPU efficiency core 1", group: .cpu, kind: .temperature, chips: [.m2, .m2Pro, .m2Max, .m2Ultra], core: true),
    CatalogSensor(key: "Tp1t", name: "CPU efficiency core 2", group: .cpu, kind: .temperature, chips: [.m2, .m2Pro, .m2Max, .m2Ultra], core: true),
    CatalogSensor(key: "Tp1p", name: "CPU efficiency core 3", group: .cpu, kind: .temperature, chips: [.m2, .m2Pro, .m2Max, .m2Ultra], core: true),
    CatalogSensor(key: "Tp1l", name: "CPU efficiency core 4", group: .cpu, kind: .temperature, chips: [.m2, .m2Pro, .m2Max, .m2Ultra], core: true),
    CatalogSensor(key: "Tp01", name: "CPU performance core 1", group: .cpu, kind: .temperature, chips: [.m2, .m2Pro, .m2Max, .m2Ultra], core: true),
    CatalogSensor(key: "Tp05", name: "CPU performance core 2", group: .cpu, kind: .temperature, chips: [.m2, .m2Pro, .m2Max, .m2Ultra], core: true),
    CatalogSensor(key: "Tp09", name: "CPU performance core 3", group: .cpu, kind: .temperature, chips: [.m2, .m2Pro, .m2Max, .m2Ultra], core: true),
    CatalogSensor(key: "Tp0D", name: "CPU performance core 4", group: .cpu, kind: .temperature, chips: [.m2, .m2Pro, .m2Max, .m2Ultra], core: true),
    CatalogSensor(key: "Tp0X", name: "CPU performance core 5", group: .cpu, kind: .temperature, chips: [.m2, .m2Pro, .m2Max, .m2Ultra], core: true),
    CatalogSensor(key: "Tp0b", name: "CPU performance core 6", group: .cpu, kind: .temperature, chips: [.m2, .m2Pro, .m2Max, .m2Ultra], core: true),
    CatalogSensor(key: "Tp0f", name: "CPU performance core 7", group: .cpu, kind: .temperature, chips: [.m2, .m2Pro, .m2Max, .m2Ultra], core: true),
    CatalogSensor(key: "Tp0j", name: "CPU performance core 8", group: .cpu, kind: .temperature, chips: [.m2, .m2Pro, .m2Max, .m2Ultra], core: true),
    CatalogSensor(key: "Tg0f", name: "GPU 1", group: .gpu, kind: .temperature, chips: [.m2, .m2Pro, .m2Max, .m2Ultra], core: true),
    CatalogSensor(key: "Tg0j", name: "GPU 2", group: .gpu, kind: .temperature, chips: [.m2, .m2Pro, .m2Max, .m2Ultra], core: true),
    CatalogSensor(key: "Te05", name: "CPU efficiency core 1", group: .cpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Te0L", name: "CPU efficiency core 2", group: .cpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Te0P", name: "CPU efficiency core 3", group: .cpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Te0S", name: "CPU efficiency core 4", group: .cpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Tf04", name: "CPU performance core 1", group: .cpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Tf09", name: "CPU performance core 2", group: .cpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Tf0A", name: "CPU performance core 3", group: .cpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Tf0B", name: "CPU performance core 4", group: .cpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Tf0D", name: "CPU performance core 5", group: .cpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Tf0E", name: "CPU performance core 6", group: .cpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Tf44", name: "CPU performance core 7", group: .cpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Tf49", name: "CPU performance core 8", group: .cpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Tf4A", name: "CPU performance core 9", group: .cpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Tf4B", name: "CPU performance core 10", group: .cpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Tf4D", name: "CPU performance core 11", group: .cpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Tf4E", name: "CPU performance core 12", group: .cpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Tf14", name: "GPU 1", group: .gpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Tf18", name: "GPU 2", group: .gpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Tf19", name: "GPU 3", group: .gpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Tf1A", name: "GPU 4", group: .gpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Tf24", name: "GPU 5", group: .gpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Tf28", name: "GPU 6", group: .gpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Tf29", name: "GPU 7", group: .gpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Tf2A", name: "GPU 8", group: .gpu, kind: .temperature, chips: [.m3, .m3Pro, .m3Max, .m3Ultra], core: true),
    CatalogSensor(key: "Te05", name: "CPU efficiency core 1", group: .cpu, kind: .temperature, chips: [.m4, .m4Pro, .m4Max, .m4Ultra], core: true),
    CatalogSensor(key: "Te0S", name: "CPU efficiency core 2", group: .cpu, kind: .temperature, chips: [.m4, .m4Pro, .m4Max, .m4Ultra], core: true),
    CatalogSensor(key: "Te09", name: "CPU efficiency core 3", group: .cpu, kind: .temperature, chips: [.m4, .m4Pro, .m4Max, .m4Ultra], core: true),
    CatalogSensor(key: "Te0H", name: "CPU efficiency core 4", group: .cpu, kind: .temperature, chips: [.m4, .m4Pro, .m4Max, .m4Ultra], core: true),
    CatalogSensor(key: "Tp01", name: "CPU performance core 1", group: .cpu, kind: .temperature, chips: [.m4, .m4Pro, .m4Max, .m4Ultra], core: true),
    CatalogSensor(key: "Tp05", name: "CPU performance core 2", group: .cpu, kind: .temperature, chips: [.m4, .m4Pro, .m4Max, .m4Ultra], core: true),
    CatalogSensor(key: "Tp09", name: "CPU performance core 3", group: .cpu, kind: .temperature, chips: [.m4, .m4Pro, .m4Max, .m4Ultra], core: true),
    CatalogSensor(key: "Tp0D", name: "CPU performance core 4", group: .cpu, kind: .temperature, chips: [.m4, .m4Pro, .m4Max, .m4Ultra], core: true),
    CatalogSensor(key: "Tp0V", name: "CPU performance core 5", group: .cpu, kind: .temperature, chips: [.m4, .m4Pro, .m4Max, .m4Ultra], core: true),
    CatalogSensor(key: "Tp0Y", name: "CPU performance core 6", group: .cpu, kind: .temperature, chips: [.m4, .m4Pro, .m4Max, .m4Ultra], core: true),
    CatalogSensor(key: "Tp0b", name: "CPU performance core 7", group: .cpu, kind: .temperature, chips: [.m4, .m4Pro, .m4Max, .m4Ultra], core: true),
    CatalogSensor(key: "Tp0e", name: "CPU performance core 8", group: .cpu, kind: .temperature, chips: [.m4, .m4Pro, .m4Max, .m4Ultra], core: true),
    CatalogSensor(key: "Tg0G", name: "GPU 1", group: .gpu, kind: .temperature, chips: [.m4], core: true),
    CatalogSensor(key: "Tg0H", name: "GPU 2", group: .gpu, kind: .temperature, chips: [.m4], core: true),
    CatalogSensor(key: "Tg1U", name: "GPU 1", group: .gpu, kind: .temperature, chips: [.m4Pro, .m4Max, .m4Ultra], core: true),
    CatalogSensor(key: "Tg1k", name: "GPU 2", group: .gpu, kind: .temperature, chips: [.m4Pro, .m4Max, .m4Ultra], core: true),
    CatalogSensor(key: "Tg0K", name: "GPU 3", group: .gpu, kind: .temperature, chips: [.m4, .m4Pro, .m4Max, .m4Ultra], core: true),
    CatalogSensor(key: "Tg0L", name: "GPU 4", group: .gpu, kind: .temperature, chips: [.m4, .m4Pro, .m4Max, .m4Ultra], core: true),
    CatalogSensor(key: "Tg0d", name: "GPU 5", group: .gpu, kind: .temperature, chips: [.m4, .m4Pro, .m4Max, .m4Ultra], core: true),
    CatalogSensor(key: "Tg0e", name: "GPU 6", group: .gpu, kind: .temperature, chips: [.m4, .m4Pro, .m4Max, .m4Ultra], core: true),
    CatalogSensor(key: "Tg0j", name: "GPU 7", group: .gpu, kind: .temperature, chips: [.m4, .m4Pro, .m4Max, .m4Ultra], core: true),
    CatalogSensor(key: "Tg0k", name: "GPU 8", group: .gpu, kind: .temperature, chips: [.m4, .m4Pro, .m4Max, .m4Ultra], core: true),
    CatalogSensor(key: "Tm0p", name: "Memory Proximity 1", group: .sensor, kind: .temperature, chips: [.m4, .m4Pro, .m4Max, .m4Ultra], core: false),
    CatalogSensor(key: "Tm1p", name: "Memory Proximity 2", group: .sensor, kind: .temperature, chips: [.m4, .m4Pro, .m4Max, .m4Ultra], core: false),
    CatalogSensor(key: "Tm2p", name: "Memory Proximity 3", group: .sensor, kind: .temperature, chips: [.m4, .m4Pro, .m4Max, .m4Ultra], core: false),
    CatalogSensor(key: "Tp00", name: "CPU super core 1", group: .cpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tp04", name: "CPU super core 2", group: .cpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tp08", name: "CPU super core 3", group: .cpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tp0C", name: "CPU super core 4", group: .cpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tp0G", name: "CPU super core 5", group: .cpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tp0K", name: "CPU super core 6", group: .cpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tp0O", name: "CPU performance core 1", group: .cpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tp0R", name: "CPU performance core 2", group: .cpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tp0U", name: "CPU performance core 3", group: .cpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tp0X", name: "CPU performance core 4", group: .cpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tp0a", name: "CPU performance core 5", group: .cpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tp0d", name: "CPU performance core 6", group: .cpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tp0g", name: "CPU performance core 7", group: .cpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tp0j", name: "CPU performance core 8", group: .cpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tp0m", name: "CPU performance core 9", group: .cpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tp0p", name: "CPU performance core 10", group: .cpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tp0u", name: "CPU performance core 11", group: .cpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tp0y", name: "CPU performance core 12", group: .cpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tg0U", name: "GPU 1", group: .gpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tg0X", name: "GPU 2", group: .gpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tg0d", name: "GPU 3", group: .gpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tg0g", name: "GPU 4", group: .gpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tg0j", name: "GPU 5", group: .gpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tg1Y", name: "GPU 6", group: .gpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tg1c", name: "GPU 7", group: .gpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Tg1g", name: "GPU 8", group: .gpu, kind: .temperature, chips: [.m5, .m5Pro, .m5Max, .m5Ultra], core: true),
    CatalogSensor(key: "Te05", name: "CPU efficiency core 1", group: .cpu, kind: .temperature, chips: [.a18Pro], core: true),
    CatalogSensor(key: "Te0S", name: "CPU efficiency core 2", group: .cpu, kind: .temperature, chips: [.a18Pro], core: true),
    CatalogSensor(key: "Tp05", name: "CPU performance core 1", group: .cpu, kind: .temperature, chips: [.a18Pro], core: true),
    CatalogSensor(key: "Tp0D", name: "CPU performance core 2", group: .cpu, kind: .temperature, chips: [.a18Pro], core: true),
    CatalogSensor(key: "Tg05", name: "GPU 1", group: .gpu, kind: .temperature, chips: [.a18Pro], core: true),
    CatalogSensor(key: "Tg0D", name: "GPU 2", group: .gpu, kind: .temperature, chips: [.a18Pro], core: true),
    CatalogSensor(key: "Tg0L", name: "GPU 3", group: .gpu, kind: .temperature, chips: [.a18Pro], core: true),
    CatalogSensor(key: "Tg0e", name: "GPU 4", group: .gpu, kind: .temperature, chips: [.a18Pro], core: true),
    CatalogSensor(key: "TaLP", name: "Airflow left", group: .sensor, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra, .m2, .m2Pro, .m2Max, .m2Ultra, .m3, .m3Pro, .m3Max, .m3Ultra, .m4, .m4Pro, .m4Max, .m4Ultra, .m5, .m5Pro, .m5Max, .m5Ultra, .a18Pro], core: false),
    CatalogSensor(key: "TaRF", name: "Airflow right", group: .sensor, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra, .m2, .m2Pro, .m2Max, .m2Ultra, .m3, .m3Pro, .m3Max, .m3Ultra, .m4, .m4Pro, .m4Max, .m4Ultra, .m5, .m5Pro, .m5Max, .m5Ultra, .a18Pro], core: false),
    CatalogSensor(key: "TH0x", name: "NAND", group: .system, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra, .m2, .m2Pro, .m2Max, .m2Ultra, .m3, .m3Pro, .m3Max, .m3Ultra, .m4, .m4Pro, .m4Max, .m4Ultra, .m5, .m5Pro, .m5Max, .m5Ultra, .a18Pro], core: false),
    CatalogSensor(key: "TB1T", name: "Battery 1", group: .system, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra, .m2, .m2Pro, .m2Max, .m2Ultra, .m3, .m3Pro, .m3Max, .m3Ultra, .m4, .m4Pro, .m4Max, .m4Ultra, .m5, .m5Pro, .m5Max, .m5Ultra, .a18Pro], core: false),
    CatalogSensor(key: "TB2T", name: "Battery 2", group: .system, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra, .m2, .m2Pro, .m2Max, .m2Ultra, .m3, .m3Pro, .m3Max, .m3Ultra, .m4, .m4Pro, .m4Max, .m4Ultra, .m5, .m5Pro, .m5Max, .m5Ultra, .a18Pro], core: false),
    CatalogSensor(key: "TW0P", name: "Airport", group: .system, kind: .temperature, chips: [.m1, .m1Pro, .m1Max, .m1Ultra, .m2, .m2Pro, .m2Max, .m2Ultra, .m3, .m3Pro, .m3Max, .m3Ultra, .m4, .m4Pro, .m4Max, .m4Ultra, .m5, .m5Pro, .m5Max, .m5Ultra, .a18Pro], core: false),
    CatalogSensor(key: "VCAC", name: "CPU IA", group: .cpu, kind: .voltage, chips: nil, core: false),
    CatalogSensor(key: "VCSC", name: "CPU System Agent", group: .cpu, kind: .voltage, chips: nil, core: false),
    CatalogSensor(key: "VC%C", name: "CPU Core %", group: .cpu, kind: .voltage, chips: nil, core: false),
    CatalogSensor(key: "VCTC", name: "GPU Intel Graphics", group: .gpu, kind: .voltage, chips: nil, core: false),
    CatalogSensor(key: "VG0C", name: "GPU", group: .gpu, kind: .voltage, chips: nil, core: false),
    CatalogSensor(key: "VM0R", name: "Memory", group: .system, kind: .voltage, chips: nil, core: false),
    CatalogSensor(key: "Vb0R", name: "CMOS", group: .system, kind: .voltage, chips: nil, core: false),
    CatalogSensor(key: "VD0R", name: "DC In", group: .sensor, kind: .voltage, chips: nil, core: false),
    CatalogSensor(key: "VP0R", name: "12V rail", group: .sensor, kind: .voltage, chips: nil, core: false),
    CatalogSensor(key: "Vp0C", name: "12V vcc", group: .sensor, kind: .voltage, chips: nil, core: false),
    CatalogSensor(key: "VV2S", name: "3V", group: .sensor, kind: .voltage, chips: nil, core: false),
    CatalogSensor(key: "VR3R", name: "3.3V", group: .sensor, kind: .voltage, chips: nil, core: false),
    CatalogSensor(key: "VV1S", name: "5V", group: .sensor, kind: .voltage, chips: nil, core: false),
    CatalogSensor(key: "VV9S", name: "12V", group: .sensor, kind: .voltage, chips: nil, core: false),
    CatalogSensor(key: "VeES", name: "PCI 12V", group: .sensor, kind: .voltage, chips: nil, core: false),
    CatalogSensor(key: "IC0R", name: "CPU High side", group: .sensor, kind: .current, chips: nil, core: false),
    CatalogSensor(key: "IG0R", name: "GPU High side", group: .sensor, kind: .current, chips: nil, core: false),
    CatalogSensor(key: "ID0R", name: "DC In", group: .sensor, kind: .current, chips: nil, core: false),
    CatalogSensor(key: "IBAC", name: "Battery", group: .sensor, kind: .current, chips: nil, core: false),
    CatalogSensor(key: "IDBR", name: "Brightness", group: .sensor, kind: .current, chips: nil, core: false),
    CatalogSensor(key: "IU1R", name: "Thunderbolt Left", group: .sensor, kind: .current, chips: nil, core: false),
    CatalogSensor(key: "IU2R", name: "Thunderbolt Right", group: .sensor, kind: .current, chips: nil, core: false),
    CatalogSensor(key: "PC0C", name: "CPU Core", group: .cpu, kind: .power, chips: nil, core: false),
    CatalogSensor(key: "PCAM", name: "CPU Core (IMON)", group: .cpu, kind: .power, chips: nil, core: false),
    CatalogSensor(key: "PCPC", name: "CPU Package", group: .cpu, kind: .power, chips: nil, core: false),
    CatalogSensor(key: "PCTR", name: "CPU Total", group: .cpu, kind: .power, chips: nil, core: false),
    CatalogSensor(key: "PCPT", name: "CPU Package total", group: .cpu, kind: .power, chips: nil, core: false),
    CatalogSensor(key: "PCPR", name: "CPU Package total (SMC)", group: .cpu, kind: .power, chips: nil, core: false),
    CatalogSensor(key: "PC0R", name: "CPU Computing high side", group: .cpu, kind: .power, chips: nil, core: false),
    CatalogSensor(key: "PC0G", name: "CPU GFX", group: .cpu, kind: .power, chips: nil, core: false),
    CatalogSensor(key: "PCEC", name: "CPU VccEDRAM", group: .cpu, kind: .power, chips: nil, core: false),
    CatalogSensor(key: "PCPG", name: "GPU Intel Graphics", group: .gpu, kind: .power, chips: nil, core: false),
    CatalogSensor(key: "PG0C", name: "GPU", group: .gpu, kind: .power, chips: nil, core: false),
    CatalogSensor(key: "PG0R", name: "GPU 1", group: .gpu, kind: .power, chips: nil, core: false),
    CatalogSensor(key: "PG1R", name: "GPU 2", group: .gpu, kind: .power, chips: nil, core: false),
    CatalogSensor(key: "PCGC", name: "Intel GPU", group: .gpu, kind: .power, chips: nil, core: false),
    CatalogSensor(key: "PCGM", name: "Intel GPU (IMON)", group: .gpu, kind: .power, chips: nil, core: false),
    CatalogSensor(key: "PC3C", name: "RAM", group: .sensor, kind: .power, chips: nil, core: false),
    CatalogSensor(key: "PPBR", name: "Battery", group: .sensor, kind: .power, chips: nil, core: false),
    CatalogSensor(key: "PDTR", name: "DC In", group: .sensor, kind: .power, chips: nil, core: false),
    CatalogSensor(key: "PMTR", name: "Memory Total", group: .sensor, kind: .power, chips: nil, core: false),
    CatalogSensor(key: "PSTR", name: "System Total", group: .sensor, kind: .power, chips: nil, core: false),
    CatalogSensor(key: "PU1R", name: "Thunderbolt Left", group: .sensor, kind: .power, chips: nil, core: false),
    CatalogSensor(key: "PU2R", name: "Thunderbolt Right", group: .sensor, kind: .power, chips: nil, core: false),
    CatalogSensor(key: "PDBR", name: "Power Delivery Brightness", group: .sensor, kind: .power, chips: [.m1, .m1Pro, .m1Max, .m1Ultra, .m4, .m4Pro, .m4Max, .m4Ultra], core: false),
    CatalogSensor(key: "PBwo", name: "Display Backlight", group: .sensor, kind: .power, chips: [.m5, .m5Pro, .m5Max, .m5Ultra, .a18Pro], core: false),
    CatalogSensor(key: "pACC MTR Temp Sensor%", name: "CPU performance core %", group: .cpu, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "eACC MTR Temp Sensor%", name: "CPU efficiency core %", group: .cpu, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "GPU MTR Temp Sensor%", name: "GPU core %", group: .gpu, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "SOC MTR Temp Sensor%", name: "SOC core %", group: .sensor, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "ANE MTR Temp Sensor%", name: "Neural engine %", group: .sensor, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "ISP MTR Temp Sensor%", name: "Image Signal Processor %", group: .sensor, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "PMGR SOC Die Temp Sensor%", name: "Power manager die %", group: .sensor, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "PMU tdev%", name: "Power management unit dev %", group: .sensor, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "PMU tdie%", name: "Power management unit die %", group: .sensor, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "gas gauge battery", name: "Battery", group: .sensor, kind: .temperature, chips: nil, core: false),
    CatalogSensor(key: "NAND CH% temp", name: "Disk %s", group: .gpu, kind: .temperature, chips: nil, core: false),
]
